### ISSUE TITLE
为什么在index.ts 导入之后就会报错

### ISSUE THREAD

**Issue by SenyFish** [s-theo/lumen#137]
在/ theme/index.ts文件下加入代码
import '@theojs/lumen/theme'
网页就会报错，不知道为啥

**Comment by s-theo** [comment]
提供下 theme/index.ts 的代码

**Comment by SenyFish** [comment]
> 提供下 theme/index.ts 的代码
我重新建了一个vitepress项目，然后正常，我之前是导入了一个第三方主题，后来发现打包不了，使用pnpm uninstall命令把它删了，应该是有些文件没有成功删除，导致你的主题和上一个主题冲突了
