### ISSUE TITLE
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by SenyFish** [s-theo/lumen#142]
某些Sass JS API即将废弃，希望修复一下，谢谢
![image](https://github.com/user-attachments/assets/18664ea6-0b29-4284-8c97-d26b8260e2ef)

**Comment by SenyFish** [comment]
可以正常运行项目，但是希望作者能够修复一下谢谢

**Comment by s-theo** [comment]
vite 还没有使用新版的API 想要消除警告查看https://tools.theojs.cn/guide/getting-started#%E5%AE%89%E8%A3%85 弃用警告部分

**Comment by SenyFish** [comment]
> vite 还没有使用新版的API 想要消除警告查看https://tools.theojs.cn/guide/getting-started#%E5%AE%89%E8%A3%85 弃用警告部分

好的不好意思，我以为是你组件的问题
