### ISSUE TITLE
 图片描述 无法实现效果

### ISSUE THREAD

**Issue by SenyFish** [s-theo/lumen#143]
[config.md](https://github.com/user-attachments/files/17829769/config.md)
[index.md](https://github.com/user-attachments/files/17829765/index.md)
这是我的配置文件（实际后缀名是.ts），能否查看我的配置哪里出错了呢？
![image](https://github.com/user-attachments/assets/3072b9be-c1f9-4b53-92b7-5ad6f69af3cc)
![image](https://github.com/user-attachments/assets/5a6c805e-18d4-483e-b026-38509461004f)

**Comment by s-theo** [comment]
先注释`import './style.css'` 然后再检查图片和下一行文字是否间隔一行

**Comment by SenyFish** [comment]
> 先注释`import './style.css'` 然后再检查图片和下一行文字是否间隔一行

和之前一样，没有间隔一行

**Comment by s-theo** [comment]
提供完整仓库 或使用 [vitepress.new](https://vitepress.new/) 复现

**Comment by SenyFish** [comment]
> 提供完整仓库 或使用 [vitepress.new](https://vitepress.new/) 复现

你好，这是我的项目仓库地址:https://github.com/ginitaimeiyty/blog

**Comment by s-theo** [comment]
```diff
// .vitepress/config.mts
import { defineConfig } from 'vitepress';
+ import { figure } from '@mdit/plugin-figure'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "Mr.🐟",
  titleTemplate: 'Home',
  lastUpdated:true,
  description: "技术博客",
+  markdown: {
+   config: (md) => { 
+      md.use(figure, { figcaption: 'alt', copyAttrs: '^class$', lazy: true }) 
+    } 
+  } ,
```


```md
// zucheng.md
![效果图](/OSI.jpg)

# 计算机组成原理
```


<img width="832" alt="image" src="https://github.com/user-attachments/assets/27ade921-c7ab-4056-b020-7c808c0e5339">

**Comment by ginitaimeiyty** [comment]
> ```diff
> import { figure } from '@mdit/plugin-figure'
> ```
还是没有效果，最新的更改已经提交到仓库，麻烦你再看一下

**Comment by SenyFish** [comment]
> ```diff
> // .vitepress/config.mts
> import { defineConfig } from 'vitepress';
> + import { figure } from '@mdit/plugin-figure'
> 
> // https://vitepress.dev/reference/site-config
> export default defineConfig({
>   title: "Mr.🐟",
>   titleTemplate: 'Home',
>   lastUpdated:true,
>   description: "技术博客",
> +  markdown: {
> +   config: (md) => { 
> +      md.use(figure, { figcaption: 'alt', copyAttrs: '^class$', lazy: true }) 
> +    } 
> +  } ,
> ```
> 
> ```
> // zucheng.md
> ![效果图](/OSI.jpg)
> 
> # 计算机组成原理
> ```
> 
> <img alt="image" width="832" src="https://private-user-images.githubusercontent.com/89436345/388321769-27ade921-c7ab-4056-b020-7c808c0e5339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODYxMjAsIm5iZiI6MTczMjE4NTgyMCwicGF0aCI6Ii84OTQzNjM0NS8zODgzMjE3NjktMjdhZGU5MjEtYzdhYi00MDU2LWIwMjAtN2M4MDhjMGU1MzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEwNDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNTBiZGFlM2Q2NjE4Y2RmYjQ0NzVhNDc3NjQ1YjlhNDI3NWU1YTIyZTE4NjMzZjZkZDNhZDY3ZWU0NWEwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dF4ZRedxGrRXbPs9D-61DwOGv7Ps15YMkzXTWiTvgWQ">

还是没有效果，最新的更改已经提交到仓库，麻烦你再看一下

**Comment by s-theo** [comment]
没什么问题
<img width="396" alt="image" src="https://github.com/user-attachments/assets/aaa24f53-d7b5-4981-85a3-b76e239d8073">
<img width="781" alt="image" src="https://github.com/user-attachments/assets/a30df15d-e937-4bb7-a35a-4e44531f9bb5">
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/8523029f-b8ed-409d-b168-c890273e8f5f">

**Comment by SenyFish** [comment]
这个图片描述是只能网页的头图才能实现是吧？我以为在文字中插入也能实现，看来是我误解了你的意思，顺便问一下如何才能扩展你的主题？

**Comment by s-theo** [comment]
> 这个图片描述是只能网页的头图才能实现是吧？我以为在文字中插入也能实现，看来是我误解了你的意思，顺便问一下如何才能扩展你的主题？

文档中都可以使用 只不过不能与文字同行插入

另外拓展什么内容

**Comment by SenyFish** [comment]
> > 这个图片描述是只能网页的头图才能实现是吧？我以为在文字中插入也能实现，看来是我误解了你的意思，顺便问一下如何才能扩展你的主题？
> 
> 文档中都可以使用 只不过不能与文字同行插入
> 
> 另外拓展什么内容

我想给hero部分的image背景添加呼吸灯效果、还有鼠标滑过features时的渐变效果
![c83e78ffab3cf0c4300393563dff096](https://github.com/user-attachments/assets/82aa84a7-e19b-4ac9-9d23-cc9009ef371e)
这些效果是靠这个第三方主题来实现的：https://www.npmjs.com/package/@escook/vitepress-theme
但是导入这个第三方主题后无法build，会报错：
![image](https://github.com/user-attachments/assets/2be8f156-6ca0-4cbc-8306-e6541aea162a)
因本人能力十分有限所以才放弃使用这个主题，但是又想复刻部分效果，所以来寻求你的帮助

**Comment by s-theo** [comment]
可以一起使用,但是会有一些样式没有正确显示 
```ts
// https://vitepress.dev/guide/custom-theme

// import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'
import { h } from 'vue'

import '@theojs/lumen/theme'
import { Twikoo,Announcement,HomeUnderline,DocAsideLogo,HomeFooter,DocBox, DocLinks, DocBoxCube } from '@theojs/lumen'
import { Twikoo_Data } from '../data/Twikoo'
import { Aside_Data } from '../data/AsideData'
import { Footer_Data } from '../data/footerData'

import '@escook/vitepress-theme/style.css'
import Theme from '@escook/vitepress-theme'


export default {
  extends: DefaultTheme,
  Layout: () => {
    return h(Theme.Layout, null, {
      'doc-after': () => h(Twikoo, { Twikoo_Data }),
      'home-hero-info-before': () => h(Announcement) ,
      'aside-ads-before': () => h(DocAsideLogo, { Aside_Data }),
      'layout-bottom': () => h(HomeFooter, { Footer_Data }) 
    }) 
  },
  enhanceApp: ({ app }) => {    
    app.component('Home', HomeUnderline) 
    app.component('Box', DocBox)
    app.component('Links', DocLinks)
    app.component('BoxCube', DocBoxCube)
    app.component('Twikoo', Twikoo)
  } 
}
```

**Comment by SenyFish** [comment]
> 可以一起使用,但是会有一些样式没有正确显示
> 
> ```ts
> // https://vitepress.dev/guide/custom-theme
> 
> // import type { Theme } from 'vitepress'
> import DefaultTheme from 'vitepress/theme'
> import { h } from 'vue'
> 
> import '@theojs/lumen/theme'
> import { Twikoo,Announcement,HomeUnderline,DocAsideLogo,HomeFooter,DocBox, DocLinks, DocBoxCube } from '@theojs/lumen'
> import { Twikoo_Data } from '../data/Twikoo'
> import { Aside_Data } from '../data/AsideData'
> import { Footer_Data } from '../data/footerData'
> 
> import '@escook/vitepress-theme/style.css'
> import Theme from '@escook/vitepress-theme'
> 
> 
> export default {
>   extends: DefaultTheme,
>   Layout: () => {
>     return h(Theme.Layout, null, {
>       'doc-after': () => h(Twikoo, { Twikoo_Data }),
>       'home-hero-info-before': () => h(Announcement) ,
>       'aside-ads-before': () => h(DocAsideLogo, { Aside_Data }),
>       'layout-bottom': () => h(HomeFooter, { Footer_Data }) 
>     }) 
>   },
>   enhanceApp: ({ app }) => {    
>     app.component('Home', HomeUnderline) 
>     app.component('Box', DocBox)
>     app.component('Links', DocLinks)
>     app.component('BoxCube', DocBoxCube)
>     app.component('Twikoo', Twikoo)
>   } 
> }
> ```

所以我现在想把它配置这些界面的代码拉出来，然后从你的主题进行扩展，因为我不知道两个主题一块儿用会不会引发什么特殊的bug

**Comment by s-theo** [comment]
目前只发现'@escook/vitepress-theme/style.css'中的 `.vp-doc img` 冲突 注释掉即可

**Comment by SenyFish** [comment]
> 目前只发现'@escook/vitepress-theme/style.css'中的 `.vp-doc img` 冲突 注释掉即可

但是好像无法实现鼠标移到features时的渐变效果，请问这个是通过什么来实现的呢？

**Comment by s-theo** [comment]
需要引入`@escook/vitepress-theme/style.css` 或者是自己编写css

**Comment by SenyFish** [comment]
> 需要引入`@escook/vitepress-theme/style.css` 或者是自己编写css

好吧，我自己学习一下，谢谢你的答复，再见
