### ISSUE TITLE
页脚的优化建议

### ISSUE THREAD

**Issue by ikenxuan** [s-theo/lumen#15]
感谢@theojs/lumen优美的组件给予我的站点二次新生。但是我觉得有些地方还可以更好！

* data中的备案字段应为可选项。
* 页脚组件中的备案信息如果data中没有相关字段，应该在前端不加载相关div（移除相关字段后的状态是无法加载主页，一片空白）。
* 当备案信息为：

```ts
beian: { icp: '', police: '' }
```

的时候，前端页面应该也需要移除相关的占位符。
![image](https://github.com/user-attachments/assets/c18ec6e6-cba1-4a0e-864a-0b998668ebcf)

**Comment by s-theo** [comment]
[最新版本](https://github.com/Theo-Messi/tools/releases/tag/Lumen%402.6.3)中已经修复了
