### ISSUE TITLE
提问：能不能让导航栏一个颜色
现在是左侧边栏顶部的logo导航栏两个色
能不能美化成一个颜色的，技术限制修改css之后不兼容


### ISSUE THREAD

**Issue by seraluce** [s-theo/lumen#179]

**Comment by s-theo** [comment]
如果是说图片中的颜色的话 不支持
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/70dfd08f-8498-47c3-84e7-2e78d1d7a57e" />
