### ISSUE TITLE
DocPill wont import 

### ISSUE THREAD

**Issue by VGSS6102** [s-theo/lumen#187]
I've noticed that your plugin has been updated to 5.0.2 and you added new link card Pill https://lumen.theojs.cn/guide/linkcard#pill.
So I updated the plugin to 5.0.2 but when I tried to import new link card it says there's no such thing.

![{8D5FCDDA-9D5C-4119-90D1-6DDE5AB89F14}](https://github.com/user-attachments/assets/6630fae5-3bc9-471a-8876-fa72afd8e50d)

I used `npm fund` to double check if versions are correct and they are.

Thanks for help in advance!

**Comment by s-theo** [comment]
need to wait for the next version

**Comment by VGSS6102** [comment]
Oh ok, thank you!
