### ISSUE TITLE
希望作者大大优化一下Box,BoxLink

### ISSUE THREAD

**Issue by xulei131401** [s-theo/lumen#24]
希望增加一个属性，可以控制 _blank 还是_self

**Comment by s-theo** [comment]
> 希望增加一个属性，可以控制 _blank 还是_self

我觉得不应该加属性,直接做个判断就好了 
当链接开头为http或者https的时候 用`_blank`
否则就用`_self`

**Comment by xulei131401** [comment]
可以的 # @Theo-Messi

**Comment by s-theo** [comment]
已经修复并发版了
